
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import static org.junit.Assert.assertEquals;

import org.junit.Test;

import filesystem.XHash;

public class LibraryTest {

	@Test
	public void testhash() {
		assertEquals(1430641242, XHash.Hash("D:\\levazým\\base\\ofc2007.rar"));
	}
}
