
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import filesystem.XHash;

import static org.junit.Assert.*;

import org.junit.Test;

public class LibraryTest {

	@Test
	public void testhash() {
		assertEquals(1430641242, XHash.Hash("D:\\levazým\\base\\ofc2007.rar"));
	}
}
